SecurityGroupPorts:
- '8080'
RuntimeType: Container
ServicePorts:
- '8080'
ServiceType: private
ArtifactSourceType: Buildpacks
ServiceBuildRegion: ap-southeast-1
RepoName: mengjunwei-mjw/java-springboot-demo
RegionId: cn-hangzhou
CustomParameters: ''
Owner: mengjunwei-mjw
Branch: main
Platform: github
