RepoName: mengjunwei-mjw/java-springboot-demo
RunCommand: |
  echo "start run command"
SourceCodePath: .
CommandTimeout: 3600
SecurityGroupPorts:
- 80
RuntimeType: LinuxShell
ServicePorts:
- 80
ServiceType: private
ArtifactSourceType: SourceCode
ImageId: '"{{resolve:oos:aliyun/services/ecs/images/linux/ubuntu-latest/ubuntu_22_04_x64}}"'
ServiceBuildRegion: ap-southeast-1
RegionId: cn-hangzhou
CustomParameters: ''
Owner: mengjunwei-mjw
Branch: main
Platform: github
